# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('author', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('on_shelf', 'On Shelf'), ('lended', 'Lended')], default='on_shelf', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.Book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.Borrower')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='current_lending',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shelf.Lending'),
        ),
    ]
