# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20160807_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
